language: node_js
node_js:
- 8.4.0
branches:
  only:
  - master
before_deploy:
- echo 'ready?'
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: R+mpCWvqWPO+09NjnGGmdPtLGQ5cEarRcf3NRiqNTOw65AXRbj9dELiLl/v7cegvRIRuY5RreUQKAx8uDW7R/P3174r+jG1hi0M+fSkpaiEHUYvfv1RQ1kkj70t+kHxYzR7hzCFIU1r14FlDMDu/1nAdx0itktqoksHM9N4OhidVAabf4PeRCqM+EdXOVcGHVA3Yh3yK2t8Zkr0E5K2VGxrC0aKwbq7yWwUrS0Todx33I9rXo189qrhaJkP5AoO9Obarl9kLsHaRg8ImD7Blu1CyM6JwYukkxZyuKiY+IbkaPHXeTLU5WD/2GAwRU9xOWWDLkz8nkh+bFRcgBSbp/YXPhIvuz6WY+6SP6S9JxbwOniRCSqQZS8sAZhKqEdIJS7lIW5LFfqFDRl0C8XnS61rhRpdGoCu9LwUTTnpjY9e6REobMe5q19JbIt2oHQUtIwSSQ/Gz6IZbsPOfwg5DiunlFcT3YJfn5gdtgVnEN6WdyoxCeND9q4gw+jEWxHdNzZN1m/6raujALHxdaBVyBZWAv/iGorGxE+H2z9pxn3HZgdrgADjf3IaQtRb0MseWWEALRh1lT0axA0IFtjngkGTigDOn18AP/QyTgc0+PvmDh0N/zInVa/trocHv1m1DVJDyWBhVJPRi2oG5fwXZJXVt9ZmNKR9sYAlCKZ7RXFI=
  project: hostingv2
