language: node_js
node_js:
- 8.4.0
before_deploy:
- echo 'ready?'
- npm run build
deploy:
  provider: firebase
  token:
    secure: dV8RPyqvrPC6CtMzXIO0HPrrBOKw6qDJNnq7YuaRrXm/CwZv/xAUSaFfNKcwZOzfQr45B9JIWKzqGInonaqnRgg/Jp1HvuuruIhsWjC6ofhNjphs12kWpEZ1Ad7e4zS4VpZrMwBH5TIbIoVwgBgkTrazyk8VYsKYpIqVNKIUgewtSzYTsi2cUfjTRS0B+PjX725JTF7ynVF9wHBVbRSN5PzK6VfLMl8ol+pyF9/R+g/pgOXlnwbmDlpV3hrA29R+nO/VbL2FghoR3jRJoGl0+PbNp7muVwid4u0eYlNZoSNHP9KBzeN2XV6tT/70poyL5wF7Rh/lwONjkMXC+PVD1dig/d58YjvE1K5vW4NrhJIPU+xhKcP5GR8cjyztEFXR/0I93u+/IupH1bwUP5oxLaCmKZffPwfASACytmJBAsBUpvsb2jPe8cwOGtZC4pbIhEzte1LzwnDDZ9k+q96bIpRLoxgHxGPm4BmcWjTas3mYLCVDmKxlrxOz67aKkndIzLyKeLhw3bJbGBg/px5Nvq4aPFOom9vagiG4NUt9CfA3KSOOebKk+EeotKlB3blfOrwosRy9AsDtB0MtUwOfG/bwOYPCqXiuVJGSBQXE1BFPbtNOEJQJ/+LG3zLFszfjbyDG5vKo1Iz/W+QgOTaJpy1ORODhHrUcLeNRrVrOmo0=
  project: "hostingv2"
