language: node_js
node_js:
  - "8.4.0"
install:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project hostingv2