language: node_js
node_js:
  - "8.4.0"
install:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run build
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  # - firebase deploy --token $FIREBASE_TOKEN --project hostingv2
  - firebase deploy --token $FIREBASE_TOKEN --project staging
  - npm run lh $STAGING_URL
