<template>
  <div class="home">
    <img src="../assets/logo.png">
    <p>
      <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas unde dolor ipsum? Minima magni veritatis nulla ipsam voluptatem nemo quam nam sapiente, unde similique totam molestiae quis asperiores doloribus libero nobis dolorem repellendus fugit esse odio explicabo possimus iusto tempore repudiandae? Vitae pariatur fuga repellendus quibusdam mollitia! Laboriosam sequi maxime dolore sed. Alias reiciendis quidem nulla fugiat est rerum voluptate autem labore amet dolore maiores neque velit nam aut, soluta placeat repellendus quo laboriosam ut. Assumenda deserunt ipsam ea dolore non eius adipisci magni dolorum, placeat eligendi temporibus ab ratione magnam nam minima eveniet nisi numquam odio commodi! Aliquam, ad.</span>
      <span>Architecto maiores eaque laudantium dignissimos ut dolores consectetur corporis consequatur unde illo minima aliquid blanditiis iusto, molestias error, quam alias itaque. Reprehenderit minima eveniet atque corporis perspiciatis porro adipisci rem, iusto, sint placeat vitae impedit temporibus. Facere odio eius provident sunt laudantium libero dolorum delectus, quibusdam, nulla consequatur quidem eveniet at recusandae animi veniam quia accusantium mollitia reiciendis ea. Reprehenderit repellendus quisquam ex. Placeat voluptatem, temporibus eum mollitia eligendi, vitae minima voluptates magni nihil veniam laborum. Similique ab, voluptate laborum ad consectetur esse repellat sint, quo ullam dicta deleniti earum odit, veritatis dignissimos aut a eaque nam quam? Fugiat, vel?</span>
      <span>Eius recusandae molestias a vitae cupiditate, excepturi quos ipsum quidem corrupti corporis nostrum nesciunt veritatis voluptatem hic impedit iure harum perferendis commodi repellendus vel. Totam suscipit vitae fugit porro quo laborum ab repellat qui nulla consequatur debitis esse, illo minima nisi doloremque impedit eum nobis ut laboriosam pariatur iusto quia. Amet laborum odio eum dolorum dolor ullam, voluptatibus, dolore nemo quia voluptas maiores eius exercitationem odit. Fugiat, laudantium maxime quae perspiciatis, quos nihil exercitationem praesentium, rem sint mollitia voluptatum nam quia aliquid qui placeat quibusdam accusantium ipsa veniam minima. Fugit repellendus quisquam voluptates explicabo illum cum odit porro voluptatibus est!</span>
      <span>Reiciendis accusamus ipsam expedita. Sed asperiores expedita sint officia voluptas modi ratione aut non quam? Aliquam dicta ipsam, nostrum earum rem alias quidem consequatur. Quia aliquam at nesciunt rem possimus molestiae maiores officiis atque saepe eligendi ad consectetur, assumenda quaerat accusamus nobis! Pariatur, ullam ipsam nihil eos voluptatibus libero hic fugit quaerat quasi suscipit architecto illum assumenda inventore impedit omnis similique minus corporis tempora tenetur delectus aliquam et blanditiis fuga reiciendis. Illum, quasi est. Distinctio fuga voluptate amet possimus fugiat dolorum architecto eaque delectus, veniam deleniti tenetur soluta tempore, reprehenderit nobis aut perferendis laudantium earum recusandae illo a obcaecati vel!</span>
      <span>Asperiores fuga recusandae similique illum distinctio natus a, expedita, blanditiis, ullam rem minus ab? Obcaecati nobis autem fugit harum quae suscipit excepturi itaque facilis architecto quidem doloribus, voluptates doloremque dicta? Ad a similique asperiores voluptatum quam, labore alias amet beatae veritatis commodi dolorem non repellendus consequatur, ratione consectetur deleniti atque. At voluptate minus optio fuga magni corporis earum sint facere nostrum minima nulla unde eaque amet ratione vitae, quis animi nam voluptatem provident labore laboriosam. Expedita voluptatum, perspiciatis reprehenderit ea magnam quidem recusandae assumenda eligendi cupiditate, sit ipsum odio. Voluptates accusantium consequuntur, corporis eaque obcaecati porro quaerat debitis sed praesentium.</span>
      <span>Reiciendis aliquid unde animi! Sed minima in et voluptas at non soluta pariatur fugit consequuntur ipsam, cumque magnam accusantium obcaecati, amet architecto sint neque culpa sunt fuga rem veritatis. Earum ea accusamus, dolor delectus corporis numquam quod. Vero numquam vel quos inventore. Recusandae accusantium voluptas, quae nostrum consequatur, quia pariatur non, ducimus corporis repudiandae doloremque ex aliquid minus sequi dolore tempora quam ipsa assumenda eius cum libero eaque deserunt corrupti odit. Esse nobis tempora atque excepturi quia hic debitis consectetur cumque, perspiciatis sit iure saepe doloremque quisquam vel quo corporis harum ad neque asperiores reprehenderit est dolor modi nam aperiam.</span>
      <span>Vitae consectetur odio impedit consequatur facilis doloremque expedita est nam, sed ipsum atque natus accusamus temporibus, unde tempore. Modi quasi necessitatibus nesciunt in, facilis vitae ipsam unde eaque voluptatem similique totam nam dolores. Tempora porro eligendi, molestiae ut debitis ipsam deleniti repudiandae ullam non quos quod possimus beatae explicabo quae fugit dolorem nemo odit neque provident distinctio nostrum necessitatibus, ab facere culpa? Sapiente, nobis. Cupiditate aperiam error illo vel magnam nulla saepe vero tenetur. Sapiente eligendi soluta animi debitis perspiciatis consectetur, quo exercitationem? Provident veniam neque animi ducimus exercitationem quasi obcaecati alias, aliquid ab, quos eum deleniti ipsam perferendis consectetur!</span>
      <span>Dolorum ullam, aliquid ipsa minus sit aut optio repellat, minima cumque dolores id nam tempore in laborum accusamus nihil nostrum quam doloribus quae perspiciatis earum? Quas expedita, nisi rem deleniti enim magnam aut voluptatum quae consequuntur corporis cumque maxime quasi exercitationem ex perspiciatis iusto labore molestiae aperiam quod eos modi tenetur nemo corrupti natus? Aut reiciendis natus harum. Aspernatur dolorum nulla in animi corporis numquam hic velit et eveniet, nihil minus cum illo fugit doloribus saepe itaque aperiam voluptatibus ab! Doloremque unde aliquid eius autem molestiae, adipisci ipsam exercitationem a veniam, cum voluptate debitis animi quae expedita voluptatum similique quia?</span>
      <span>Unde esse ex recusandae quod neque, similique nobis non veniam iste dolorum tempora at modi voluptates nostrum dolores, aspernatur voluptatem exercitationem? Necessitatibus sit voluptate, harum quas earum illum consequuntur! Illo ullam omnis commodi odio officia culpa est iusto unde quos, quasi quibusdam, ipsum libero nihil molestias. Architecto laudantium rerum optio delectus beatae dolor itaque ratione sed amet. Quasi ducimus, velit atque vitae iure dolore corrupti nemo voluptatibus modi veritatis eveniet sunt eum officia natus neque praesentium nostrum nihil possimus consectetur non. Voluptates, asperiores similique fugit in ut debitis cum iusto dicta alias, corporis delectus? Ducimus illo alias voluptas nihil quidem!</span>
      <span>Maiores iste voluptates libero, quae officiis eveniet non! Quibusdam maxime porro doloremque culpa eius quasi in commodi error excepturi cupiditate, sunt voluptate a. Fugiat pariatur sint velit facilis laudantium dignissimos cupiditate veniam temporibus rerum, ullam odio harum provident quod voluptatum eum at quo? Praesentium commodi tempora neque sunt corrupti eligendi cumque possimus modi esse atque sit labore itaque error nobis totam vero adipisci architecto enim quaerat mollitia dicta voluptates, iste quo illo! In sit, recusandae eaque nisi iste ea ipsum odit non dolorum repellat ipsam illo rem unde labore optio quibusdam reiciendis accusantium vero enim. Soluta alias doloremque voluptas vero.</span>
      <span>Hic recusandae eos placeat, suscipit voluptatibus repellat laboriosam facilis perspiciatis sunt tempora velit voluptate corporis numquam expedita laudantium nisi vero earum libero. Debitis itaque, fugit ea, deleniti quidem iste vero nobis inventore modi voluptatum aliquid quisquam. Ipsum adipisci eaque quos tempora exercitationem quam deserunt saepe. Ad minus quam voluptatem non deleniti obcaecati. Illo odio, deleniti amet repellat molestias incidunt ipsam error cumque porro sint, eligendi obcaecati, aliquid optio fugiat atque aspernatur eveniet consequuntur! Ex nesciunt ea praesentium ipsum necessitatibus recusandae quia error deserunt vero dolorum reiciendis, sapiente explicabo iusto quasi similique quod. Quasi nisi itaque nostrum quam fugiat optio culpa.</span>
      <span>Illum molestiae expedita at quidem quam, aliquam quis quisquam, architecto veritatis asperiores sequi perferendis! Sunt eum quo, odit totam dolores cupiditate ipsum! Hic nisi sit, eius quibusdam repellat esse est vel quaerat, et nam, velit nesciunt sequi distinctio. Porro possimus obcaecati fugit similique repellendus culpa recusandae. Necessitatibus ea vel voluptas qui laudantium exercitationem. Deserunt qui repellat deleniti, odit impedit quisquam! In, dolorum ad eaque debitis velit expedita vitae ipsum sed commodi consequatur. Asperiores magnam sint assumenda voluptatem tempore dicta rem. Necessitatibus, velit quisquam, illum in molestiae magni quidem perferendis fugit dolorem, nemo nisi. Cupiditate a porro neque, perspiciatis harum similique.</span>
      <span>Dicta vel at ratione vitae esse assumenda maiores, tempora earum beatae, omnis nemo quo? Perferendis culpa reprehenderit nemo maxime corrupti eius, id, quaerat consequuntur laborum facere nihil atque aliquam dolorem! Ea rem corporis, atque exercitationem maiores sit deleniti ullam inventore animi temporibus eius dicta magni odio quos asperiores voluptatibus vel hic alias culpa quisquam. Placeat veniam totam vero maxime consectetur, odio quam molestias cum deleniti mollitia perspiciatis consequuntur iure et at quod vel modi nostrum repellat, quasi hic consequatur, asperiores voluptatum delectus? Quam illum ipsa culpa error animi adipisci tempora perspiciatis, minus vel accusantium quis numquam! Voluptates architecto sequi sed?</span>
      <span>Porro repellendus corporis eum labore doloribus, officiis nam quia exercitationem, pariatur accusantium at sint vero veritatis similique nesciunt assumenda reprehenderit? Vitae ex aspernatur recusandae! Aspernatur labore perferendis rem, neque, dolorum delectus nulla quibusdam odio dolorem consectetur, iure optio voluptates deleniti velit ratione excepturi esse eaque animi necessitatibus nostrum corrupti? Soluta rerum, nihil rem consectetur vel eum impedit quidem aliquid cupiditate laboriosam adipisci sunt corrupti expedita dolores non unde consequuntur maxime facere placeat recusandae id at nobis laudantium fugiat. Error dolore tenetur excepturi laborum non veritatis neque similique optio! Quos cumque atque distinctio ratione iusto officia perferendis earum fuga, impedit asperiores.</span>
      <span>Iste totam adipisci excepturi fugit est, quis recusandae ratione maxime veritatis voluptatum deleniti doloribus quia consequuntur at tempore! Quidem nostrum quia, amet eveniet praesentium possimus. Excepturi amet minus quaerat totam tempora sapiente sit accusamus, et, qui aliquam nisi laborum numquam iste repudiandae asperiores nulla dolorem atque labore modi alias eveniet. Quas maxime odit odio voluptatibus aspernatur mollitia, sed culpa dicta esse neque qui aut consequatur error, eos laudantium ad eum nulla quidem, officia omnis dolores sint praesentium. Consectetur quidem suscipit perferendis impedit molestiae in! Excepturi aliquid quod similique eius fugit mollitia necessitatibus tempore, illo eos est et corrupti, nesciunt dolores.</span>
      <span>Necessitatibus odit mollitia laudantium adipisci dolorum cupiditate consequuntur nobis saepe, delectus sit eum velit placeat, sunt fuga ad, sed rem error! Id eveniet quas dolor repellendus dolorem hic minus nesciunt doloribus, repellat sequi! Corporis dolore fugiat ab accusantium rem eveniet recusandae architecto velit illo officia vel qui fuga, eaque culpa ut iusto soluta voluptatibus odio, dignissimos suscipit ducimus reprehenderit nemo! Asperiores soluta repellat veniam nam quibusdam earum beatae quasi doloribus possimus harum. Alias ab dolor omnis eaque eveniet doloribus perspiciatis vero nam velit deleniti, quos iusto quam, architecto accusantium ut enim nesciunt quod repellat et nostrum? Excepturi iste obcaecati dolores.</span>
      <span>Consequuntur neque dolor quos non, eligendi modi laborum quas expedita accusamus dolores reprehenderit deleniti excepturi sed fuga quam molestiae, saepe nesciunt tenetur, ducimus animi consectetur maiores illum adipisci? Maxime, officiis sint incidunt deserunt, blanditiis corporis iure sequi at rem, numquam magni consequuntur? Sint doloremque ab tenetur amet ea obcaecati. Necessitatibus earum officiis quaerat fugiat doloribus veniam quis veritatis laudantium molestiae atque inventore vero qui cupiditate sit dolorum, ipsum natus illum quae facilis accusamus? Consequatur expedita aliquam quia! Impedit, iure sunt dolorem tempore, et quisquam sed, esse ratione minima aspernatur quaerat magnam! Cum, placeat! Molestiae, amet quis nostrum iste ab quo!</span>
      <span>Et atque optio commodi enim voluptatibus voluptatum, porro voluptates repellendus ratione hic libero mollitia dolorum quae, corrupti ut. Atque, consequuntur, magnam reprehenderit doloremque totam ratione, facere inventore sit numquam nobis assumenda? Dolorem, modi dolor sequi distinctio amet ea fuga minus nostrum provident quisquam voluptatum itaque nisi illo voluptatem perferendis commodi atque. Animi earum eveniet quos corrupti perferendis doloremque nesciunt ullam. Laudantium optio doloremque incidunt asperiores non natus quos expedita fuga quo reiciendis quisquam architecto, pariatur rem molestias officiis animi nisi recusandae quia, magni ipsa similique exercitationem aspernatur placeat? Doloribus odio earum tempora enim non, magnam soluta facere consequuntur? Iure, quo.</span>
      <span>Vitae nisi nulla omnis, laborum quod iure consectetur est et, tempora magni, voluptates ratione similique. Quidem maiores, optio eaque officia aspernatur voluptate sint fugit suscipit doloremque, pariatur eos tempore adipisci eligendi esse, incidunt nihil amet eveniet dolorem voluptates quasi? Quae dignissimos libero ab eos. Omnis accusamus sequi cum praesentium ad debitis dolorem, iste eum officiis repudiandae nulla dicta. Esse assumenda quo deleniti, in aut dignissimos. Qui optio nihil eaque tempore temporibus aut illum quis! Quia minus quos ea neque ad porro eius veniam maxime quam perferendis nobis a, molestiae suscipit accusamus non nisi amet quidem vero officiis rerum sequi perspiciatis!</span>
      <span>Sequi, corporis. Voluptas sequi aliquid, saepe doloremque animi sed ut. Harum quae voluptate consequatur. Eveniet amet, corporis accusamus a ad fugit officia laudantium, assumenda expedita praesentium ut consectetur non dicta, porro enim tempora eum? Numquam quia repellat ipsam tenetur. Assumenda, magni. Nobis delectus saepe quis numquam fuga quibusdam, modi iste libero nemo architecto reprehenderit assumenda sint placeat cupiditate vel expedita similique autem? Voluptatem fuga assumenda, nam dolor asperiores blanditiis laudantium fugiat harum enim doloribus adipisci! Sequi ut alias doloremque earum repellat deserunt mollitia. Sapiente molestiae quam impedit odio ipsam repellendus nihil sunt dolores, maiores, necessitatibus pariatur. Nulla, vero vel. Nisi?</span>
    </p>
    <section class="red">
      i am redish
    </section>
  </div>
</template>

<script>
export default {
  name: 'home'
}
</script>

<style lang="stylus" scoped>
span {
  color: green;
}

.red {
  color: red;
}
</style>
